### ISSUE TITLE
[Sprint] Change pydantic to dataclass

### ISSUE THREAD

**Issue by Only-bottle** [Nota-NetsPresso/netspresso-python#243]
## Description

- Change the pydantic that defined the API schema to a dataclass.

## Checklists

- [x] I would create a corresponding branch for this issue from the designated (mostly `develop`) branch.
- [x] This issue only contains a preceding agreement between project owners.

**Comment by Only-bottle** [comment]
cc. @illian01 ❤️‍🔥

**Comment by paran3** [comment]
Hello @Only-bottle. I’ve updated [the auth client v2 to use dataclasses instead of pydantic](https://github.com/Nota-NetsPresso/PyNetsPresso/pull/244/commits/46db5c829a98d963a86ac774c09af02081296dcc) as we decided for PyNetspresso. 
Let me know if you have any feedback.

cc. @soyoungKo

**Comment by Only-bottle** [comment]
This issue has been resolved, so we're closing it.
