### ISSUE TITLE
Allow `fp16` input tensor to apply with `fp16` saved model

### ISSUE THREAD

**Issue by deepkyu** [Nota-NetsPresso/netspresso-python#36]
### Problem

From @illian01 

**Compressor**

- Current API gets input tensor as `input_shape`
  - [Corresponding line](https://github.com/Nota-NetsPresso/PyNetsPresso/blob/f28041ad7742a77f90df0c6b826376644546a800/netspresso/compressor/__init__.py#L52-L62) 
  - Generate input tensor with `float32` with the given size
- Some models can be saved with `half()` (i.e. `fp16`), which cannot infer with `float32` input tensor .
  - This model should give the example input tensor whose dtype is same with the model (`float16`)
- Need additional feature for users to select the data type of example input tensor
- Our back-end has already supported different input types of tensors, and it doesn't affect to compress the model

### Related Link
Slack: https://nota-workspace.slack.com/archives/C040F65LSAJ/p1693546735327899

**Comment by Only-bottle** [comment]
@deepkyu @illian01님, 해당 이슈는 Compressor Backend에서 처리하였습니다.

해결한 방식은 아래와 같습니다.
- half의 경우 cpu에서는 사용할 수 없다는 것을 확인했고([관련 issue](https://github.com/ultralytics/yolov5/issues/10379#issuecomment-1335865572)), float으로 변환해서 압축 후 half로 변환해서 제공하도록 처리하였습니다.
